### ISSUE TITLE
Remove tripledes support

### ISSUE THREAD

**Issue by Hezeh** [Flutterwave/flutterwave-flutter#49]
Currently tripledes in no longer maintained and migrating to another library might be the best option.

**Comment by FredDominant** [comment]
Hello @Hezeh, This is being looked into. Thank you for raising this.

**Comment by blackmann** [comment]
Why is this issue closed when it hasn't been resolved? Don't you think it encourages duplicate issues?

**Comment by FredDominant** [comment]
Hello @blackmann. Thank you for your comments. As you can see, it was closed with a comment. The issue was closed because it was a suggestion, and the current implementation doesn't in any way breach security or affect the performance of the application. 

We look forward to getting more of your contributions.

**Comment by blackmann** [comment]
But it affects apps that have migrated to null-safety.
